### ISSUE TITLE
(PACKED_PER_VAL=)

### ISSUE THREAD

**Issue by arthurwolf** [ali-vilab/i2vgen-xl#55]
I followed the exact instructions in the github, and get this error when trying to run the inference script:

```

(vgen) ╭─arthur at aquarelle in ~/dev/ai/i2vgen-xl on main✘✘✘ 24-01-05 - 23:41:31
╰─(vgen) ⠠⠵ python inference.py --cfg configs/t2v_infer.yaml                   on main|…5
/home/arthur/.pyenv/versions/3.7.17/lib/python3.7/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "inference.py", line 14, in <module>
    from tools import *
  File "/home/arthur/dev/ai/i2vgen-xl/tools/__init__.py", line 3, in <module>
    from .modules import *
  File "/home/arthur/dev/ai/i2vgen-xl/tools/modules/__init__.py", line 5, in <module>
    from .unet import *
  File "/home/arthur/dev/ai/i2vgen-xl/tools/modules/unet/__init__.py", line 1, in <module>
    from .unet_i2vgen import *
  File "/home/arthur/dev/ai/i2vgen-xl/tools/modules/unet/unet_i2vgen.py", line 4, in <module>
    import xformers.ops
  File "/home/arthur/.pyenv/versions/3.7.17/lib/python3.7/site-packages/xformers/ops/__init__.py", line 8, in <module>
    from .fmha import (
  File "/home/arthur/.pyenv/versions/3.7.17/lib/python3.7/site-packages/xformers/ops/fmha/__init__.py", line 10, in <module>
    from . import attn_bias, cutlass, decoder, flash, small_k, triton, triton_splitk
  File "<fstring>", line 1
    (PACKED_PER_VAL=)
                   ^
SyntaxError: invalid syntax
(vgen) ╭─arthur at aquarelle in ~/dev/ai/i2vgen-xl on main✘✘✘ 24-01-05 - 23:41:36
╰─(vgen) ⠠⠵     

```

what am I doing wrong?

thanks.

**Comment by arthurwolf** [comment]
I was able to fix the issue by finding the line in question in xformers and removing it. it was an error reporting line (I think) so removing it was not too big a problem.

**Comment by hubhub086** [comment]
I hace the same error when importing xformers.ops. Could you tell me which line to remove in xformers? I can't find it

**Comment by hubhub086** [comment]
oh, I finally find the code , thanks for your ideal!
