### ISSUE TITLE
Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by protector131090** [ali-vilab/i2vgen-xl#76]
Traceback (most recent call last):
  File "S:\i2vgen-xl\inference.py", line 18, in <module>
    INFER_ENGINE.build(dict(type=cfg_update.TASK_TYPE), cfg_update=cfg_update.cfg_dict)
  File "S:\i2vgen-xl\utils\registry.py", line 107, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "S:\i2vgen-xl\utils\registry_class.py", line 7, in build_func
    return build_from_config(cfg, registry, **kwargs)
  File "S:\i2vgen-xl\utils\registry.py", line 69, in build_from_config
    raise Exception(f"Failed to invoke function {req_type_entry}, with {e}")
Exception: Failed to invoke function <function inference_i2vgen_entrance at 0x000001F4584A1D80>, with Distributed package doesn't have NCCL built in

**Comment by 23Rj20** [comment]
Hey were you able to fix it??
