### ISSUE TITLE
[Errno 2] No such file or directory: 'workspace/model_bk/model_scope_0267000.pth'

### ISSUE THREAD

**Issue by justinday123** [ali-vilab/i2vgen-xl#77]
What is the problem. I had changed config file(which was other issue) but it doesn't helps me. Also is there no train code for modelscope?

**Comment by Steven-SWZhang** [comment]
Hi, you can refer [here](https://github.com/ali-vilab/i2vgen-xl/issues/31)

**Comment by chester256** [comment]
> Hi, you can refer to [here](https://github.com/ali-vilab/i2vgen-xl/issues/31)

Hi, the link of the previous repo is expired

**Comment by FredWe** [comment]
> > Hi, you can refer to [here](https://github.com/ali-vilab/i2vgen-xl/issues/31)
> 
> Hi, the link of the previous repo is expired

see https://github.com/alibaba/VideoMV

wget https://virutalbuy-public.oss-cn-hangzhou.aliyuncs.com/share/aigc3d/pretrained_models.zip

**Comment by Benjamin-So** [comment]
> I've made the changes suggeted on this issue [here](https://github.com/ali-vilab/i2vgen-xl/issues/31),
> 
> But I'm still getting the following error (Where am I supposed top get `'models/v2-1_512-ema-pruned.ckpt'`):
> 
> `Traceback (most recent call last): File "inference.py", line 18, in <module>` INFER_ENGINE.build(dict(type=cfg_update.TASK_TYPE), cfg_update=cfg_update.cfg_dict)`
> 
> `File "/home/luthando/Desktop/i2vgen-xl/utils/registry.py", line 107, in build return self.build_func(*args, **kwargs, registry=self)`
> 
> `File "/home/luthando/Desktop/i2vgen-xl/utils/registry_class.py", line 7, in build_func return build_from_config(cfg, registry, **kwargs)`
> 
> `File "/home/luthando/Desktop/i2vgen-xl/utils/registry.py", line 69, in build_from_config raise Exception(f"Failed to invoke function {req_type_entry}, with {e}")`
> 
> `Exception: Failed to invoke function <function inference_text2video_entrance at 0x7f0caced78b0>, with Failed to init class <class 'tools.modules.autoencoder.AutoencoderKL'>, with [Errno 2] No such file or directory: 'models/v2-1_512-ema-pruned.ckpt'`

The issue you link to is expired. What set of changes were we supposed to make?
