### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'models/v2-1_512-ema-pruned.ckpt'

### ISSUE THREAD

**Issue by saba-vaez** [ali-vilab/i2vgen-xl#93]
Hi, I’m trying to train the modelscope text to video model on the demo dataset before attempting to train it on my own dataset, but I keep getting the error below. I created a model_bk directory in the workspace folder and then cloned the model into it. I changed the resume_checkpoint path in the t2v_train.yaml file to 'workspace/model_bk/modelscope-damo-text-to-video-synthesis/text2video_pytorch_model.pth' (I also put my model in the models folder). I also changed the diffusion section based on https://github.com/ali-vilab/i2vgen-xl/issues/31. Is there anything else that I need to change in the config file? I’m a bit confused about where v2-1_512-ema-pruned.ckpt  is supposed to come from. I would really appreciate it if you could help me solve this issue.

[2024-03-01 23:43:35,481] INFO: Loading ViT-H-14 model config.
[2024-03-01 23:43:43,929] INFO: Loading pretrained ViT-H-14 weights (models/open_clip_pytorch_model.bin).
Traceback (most recent call last):
  File "/mnt/parscratch/users/aca20sv/i2vgen-xl/utils/registry.py", line 62, in build_from_config
    return req_type_entry(**cfg)
  File "/mnt/parscratch/users/aca20sv/i2vgen-xl/tools/modules/autoencoder.py", line 62, in __init__
    self.init_from_ckpt(pretrained, ignore_keys=ignore_keys)
  File "/mnt/parscratch/users/aca20sv/i2vgen-xl/tools/modules/autoencoder.py", line 65, in init_from_ckpt
    sd = torch.load(path, map_location="cpu")["state_dict"]
  File "/mnt/parscratch/users/aca20sv/anaconda/.envs/vgen/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/mnt/parscratch/users/aca20sv/anaconda/.envs/vgen/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/mnt/parscratch/users/aca20sv/anaconda/.envs/vgen/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/v2-1_512-ema-pruned.ckpt'

**Comment by anjalyv** [comment]
I downloaded this checkpoint from hugging face https://huggingface.co/stabilityai/stable-diffusion-2-1-base/blob/main/v2-1_512-ema-pruned.ckpt

**Comment by saba-vaez** [comment]
I actually did find that one but wasn't really sure it's correct. Thank you so much for confirming!
